site_name: Microcontrollers learning docs
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      linenums: true #enables line numeration
      use_pygments: true
      anchor_linenums: true #
      line_spans: __span #wraps all lines in to span for correct highlighting
      pygments_lang_class: true 
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list #without this is not possible to set image size
plugins:
  - glightbox